import json
import re
from datetime import datetime, timezone
from pathlib import Path

from app.storage import Workflow


def safe_workflow_name(title: str) -> str:
    name = re.sub(r"[^A-Za-z0-9._-]+", "_", title.strip()).strip("._-")
    return (name or "Workflow")[:80]


class WorkflowDocumentationManager:
    """Maintains local, non-secret workflow manuals and append-only process logs."""

    def __init__(self, root: Path):
        self.root = root

    def ensure(self, workflow: Workflow) -> Path:
        manual = self.root / f"{safe_workflow_name(workflow.title)}_v{workflow.revision:03d}" / "USER-MANUAL.md"
        if manual.exists():
            return manual
        return self.record(workflow, "documentation-initialized", "Manual created for an existing workflow revision.")

    def record(self, workflow: Workflow, event: str, detail: str = "") -> Path:
        now = datetime.now(timezone.utc).replace(microsecond=0)
        name = safe_workflow_name(workflow.title)
        revision_dir = self.root / f"{name}_v{workflow.revision:03d}"
        log_dir = self.root / "Logs"
        revision_dir.mkdir(parents=True, exist_ok=True)
        log_dir.mkdir(parents=True, exist_ok=True)
        safe_detail = self._safe_detail(detail)
        with (log_dir / f"{name}_{now:%Y%m%d}.log").open("a", encoding="utf-8") as stream:
            stream.write(f"{now.isoformat().replace('+00:00', 'Z')} | workflow={workflow.id} | revision={workflow.revision} | state={workflow.state} | event={self._safe_detail(event)}")
            if safe_detail:
                stream.write(f" | detail={safe_detail}")
            stream.write("\n")
        manual = revision_dir / "USER-MANUAL.md"
        temporary = revision_dir / "USER-MANUAL.tmp"
        temporary.write_text(self._manual(workflow, now), encoding="utf-8")
        temporary.replace(manual)
        return manual

    def record_test_result(self, workflow: Workflow, evidence: dict) -> Path:
        now = datetime.now(timezone.utc).replace(microsecond=0)
        revision_dir = self.root / f"{safe_workflow_name(workflow.title)}_v{workflow.revision:03d}"
        revision_dir.mkdir(parents=True, exist_ok=True)
        target = revision_dir / "TEST-RESULTS.md"
        stdout = self._safe_detail(str(evidence.get("stdout") or "")) or "[no standard output]"
        stderr = self._safe_detail(str(evidence.get("stderr") or "")) or "[no error output]"
        entry = f"""\n## Test run — {now.isoformat().replace('+00:00', 'Z')}

- Approved test-plan provider/model: `{workflow.test_plan_provider} / {workflow.test_plan_model}`
- Workflow revision: `{workflow.revision:03d}`
- Test profile: `{evidence.get('profile', 'unknown')}`
- Result: `{evidence.get('status', 'unknown')}`
- Artifact SHA-256: `{evidence.get('artifact_sha256', '')}`
- Evidence SHA-256: `{evidence.get('evidence_sha256', '')}`
- Exit code: `{evidence.get('exit_code')}`
- Duration: `{evidence.get('duration_ms', 0)} ms`
- Summary: {self._safe_detail(str(evidence.get('summary') or ''))}

### Redacted bounded output

```text
{stdout}
```

### Redacted bounded error output

```text
{stderr}
```
"""
        with target.open("a", encoding="utf-8") as stream:
            stream.write(entry)
        return target

    @staticmethod
    def _safe_detail(value: str) -> str:
        value = " ".join(value.replace("\r", " ").replace("\n", " ").split())
        value = re.sub(r"(?i)(password|secret|token|api[_ -]?key)\s*[:=]\s*\S+", r"\1=[REDACTED]", value)
        return value[:1000]

    @staticmethod
    def _manual(workflow: Workflow, generated: datetime) -> str:
        schedule = json.dumps(workflow.schedule, indent=2, sort_keys=True) if workflow.schedule else "Not configured."
        manifest = json.dumps(workflow.permission_manifest, indent=2, sort_keys=True) if workflow.permission_manifest else "Not generated."
        plan = workflow.plan_text.strip() or "The workflow plan has not been generated yet."
        questions = "\n".join(
            f"- {item.get('prompt', item.get('id', 'Question'))}: "
            f"{workflow.clarification_answers.get(str(item.get('id')), 'Unanswered')}"
            for item in workflow.clarification_questions
        ) or "No clarification questions are currently recorded."
        return f"""# {workflow.title} — User Manual

Generated by A.E.G.I.S.-9: {generated.isoformat().replace('+00:00', 'Z')}
Workflow ID: `{workflow.id}`
Transfer ID: `{workflow.transfer_id}`
Revision: `{workflow.revision:03d}`
Lifecycle state: `{workflow.state}`
Approval stage: `{workflow.approval_stage}`

## Purpose

{workflow.description.strip() or 'No user-facing purpose has been supplied yet.'}

## What this workflow does

{plan}

## How to use it

1. Confirm that the displayed revision, plan, configuration, and permission manifest are correct.
2. Complete every required clarification and explicitly approve the final workflow plan.
3. Review and approve the separately generated non-production test plans; this authorizes the build but not test execution or production use.
4. Review the generated `{workflow.language}` workflow and test artifacts, then submit them to an approved non-production test profile.
5. Review the recorded test-plan details, results, and retained evidence before accepting or rejecting the results.
6. Record the schedule, start/stop conditions, prerequisites, and purpose, then explicitly request production promotion.
7. Obtain supervisor approval for the exact revision and hashes before production execution.
8. Monitor the Workflow Center during execution. Use pause, stop, or the global kill switch when required by the runbook.

## Required information and answers

{questions}

## Configuration and schedule

```json
{schedule}
```

Credentials and secrets must be supplied through approved secret storage and are intentionally excluded from this manual.

## Permissions and safety boundaries

```json
{manifest}
```

Artifact SHA-256: `{workflow.artifact_sha256 or 'Not generated'}`
Implementation provider/model: `{workflow.implementation_provider or 'Not selected'} / {workflow.implementation_model or 'Not selected'}`

## Testing and acceptance

### Approved test plans

{workflow.test_plan_text.strip() or 'Test plans have not been generated or approved.'}

Latest test status: `{workflow.latest_test_status or 'Not tested'}`
Test evidence SHA-256: `{workflow.latest_test_evidence_sha256 or 'Not available'}`
Test summary: {workflow.latest_test_summary or 'No retained test evidence.'}

User acceptance state: `{'complete' if workflow.state in {'user_accepted', 'supervisor_pending', 'scheduled', 'queued', 'running', 'paused', 'completed'} else 'pending'}`
Supervisor: `{workflow.supervisor_approved_by or 'Not approved'}`
Supervisor approval time: `{workflow.supervisor_approved_at or 'Not approved'}`

## Process and audit log

The creation and lifecycle log is stored under `Workflows/Logs/` using the filename `{safe_workflow_name(workflow.title)}_YYYYMMDD.log`. It records stage transitions without storing credentials or implementation contents.

Detailed, redacted test execution evidence is appended to `TEST-RESULTS.md` in this revision folder.

Any material workflow edit creates a new numbered revision folder and invalidates downstream test/approval evidence according to the Workflow Center governance policy.
"""
